/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.bechberger.jfrtofp

import java.nio.file.Files
import java.nio.file.Path

fun main(args: Array<String>) {
    val json = FirefoxProfileGenerator(Path.of(args[0]), config = Config()).generateJSON()
    val jsonFile = Path.of(args[0].replace(".jfr", ".json"))
    Files.write(jsonFile, json.toByteArray())
}
