name: "pre-release"

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      packages: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTOR: ${{ github.actor }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build the project
        run: ./gradlew assemble
      - name: Publish to GitHub Packages
        run: ./gradlew publishMavenJavaPublicationToGitHubPackagesRepository
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE
            build/libs/*.jar
